### ISSUE TITLE
Maintained Turkish Translation of Python Documentation

### ISSUE THREAD

**Issue by egeakman** [OmerFI/python-docs-tr#1]
Merhaba @OmerFI, Python Dokümantasyonu Türkçe çevirisini https://github.com/python/python-docs-tr üzerinden aktif bir şekilde devam ettiriyoruz. Çeviri şu anda https://docs.python.org/tr/3 adresinde yayında. Her hafta yeni çeviriler eklemeye çalışıyoruz, sizi de aramızda görmeyi çok isteriz. Hali hazırda çevirdiğiniz dosyalarla bir pull request açmak çok güzel bir başlangıç olacaktır.

**Comment by OmerFI** [comment]
Merhaba. En kısa sürede çevirdiğim dosyalarla bir pull request açacağım😊.
İyi çalışmalar dilerim 🚀
